name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  mkdocs:
    name: Docs
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Install Hugo
        run: brew install hugo

      - name: Build docs
        run: hugo

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
        if: github.ref == 'refs/heads/main'
